import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from "../public/products.json";

export default function Home() {
  console.log('products', products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Stylz!
        </h1>

        <ul className={styles.grid}>
          {products.map(product => {
            const {id, title, description, image, price} = product;
            return (
            <li key={id} className={styles.card}>
                <img className={styles.contentImg} src={image} />
                <h2> {title}</h2>
                <p>{description}</p>
                <p>{price}</p>
            </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
